# Generated by Django 5.1.4 on 2025-01-10 07:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("business", "name"), name="unique_item_per_business"
            ),
        ),
    ]
