# Generated by Django 5.1.4 on 2025-01-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_alter_sale_payment_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expenditure",
            name="category",
        ),
        migrations.AddField(
            model_name="business",
            name="category",
            field=models.CharField(
                choices=[
                    ("bar_restaurant", "Bar & Restaurant"),
                    ("retail_wholesale", "Retail-Wholesale Shop/Store"),
                    ("service", "Service Industry"),
                    ("other", "Other (Not Listed)"),
                ],
                default="bar_restaurant",
                max_length=50,
            ),
        ),
    ]
